---
version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
    - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=supersecret
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - ./samples:/samples
    ports:
      - 5050:5050
volumes:
  db:
    driver: local
